using System.Collections.Generic;

partial class Program
{
    /// Yields each phrase plus a "phrase please" variant (skipped if the phrase already ends in "please").
    static IEnumerable<string> WithOptionalPlease(IEnumerable<string> phrases) =>
        phrases.SelectMany(p => p.EndsWith(" please") ? new[] { p } : new[] { p, p + " please" });

    static HashSet<string> GetValidCommands() =>
        new HashSet<string>
        {
            "lets prepare the aircraft",
            "lets prepare the flight",
            "lets set up the aircraft",
            "gear up",
            "gear down",
            "flaps zero",
            "flaps one",
            "flaps two",
            "flaps three",
            "flaps full",
            "landing lights on",
            "landing lights off",
            "strobe lights on",
            "strobe lights auto",
            "strobe lights off",
            "taxi lights on",
            "taxi lights off",
            "takeoff light on",
            "flight director on",
            "flight director off",
            "bird on",
            "bird off",
            "turn off bird",
            "flight director off bird on",
            "auto pilot on",
            "auto pilot one on",
            "autopilot on",
            "autopilot one on",
            "cancel checklist",
            "stop checklist",
            "abort checklist",
            "cockpit preparation checklist",
            "before start checklist",
            "before start procedure",
            "before start flow",
            "starting engine number one",
            "starting engine number two",
            "starting number one",
            "starting number two",
            "after start checklist",
            "clear left",
            "clear on the left",
            "left side clear",
            "clear left side",
            "taxi checklist",
            "departure change checklist",
            "removed",
            "line up checklist",
            "runway entry procedure",
            "clear to line up",
            "clear for takeoff",
            "before takeoff procedure",
            "takeoff",
            "approach checklist",
            "approach",
            "start approach checklist",
            "landing checklist",
            "parking checklist",
            "secure aircraft checklist",
            "ok to clean up",
            "clear to clean up",
            "lights please",
            "shutdown procedure",
            "shutdown",
            "flight controls check",
            "set",
            "released",
            "on",
            "off",
            "armed",
            "check",
            "confirmed",
            "checked",
            "set and checked",
            "received",
            "config one plus f",
            "config one plus eff",
            "config 1 plus f",
            "con fig one plus eff",
            "can fix one plus f2",
            "con fig one plus f",
            "can fix two",
            "con fig two",
            "config two",
            "config to",
            "config two",
            "config three",
            "config 3",
            "config tree",
            "config free",
            "con fig three",
            "con fig tree",
            "can fix three",
            "can fix tree",
            "advised",
            "signaled",
            "medium",
            "btv",
            "auto",
            "started",
            "running",
            "normal",
            "rto",
            "stop",
            "are tee oh",
            "r t o",
            "art o",
            "artio",
            "are tea oh",
            "tara",
            "ta ra",
            "t a r a",
            "terra",
            "zero",
            "up",
            "retracted",
            "down",
            "secured",
            "secure",
            "ta only",
            "chocks in place",
            "parking brake set",
            "wing anti ice on",
            "wing anti ice off",
            "engine anti ice on",
            "engine anti ice off",
            "starting one",
            "starting engine one",
            "starting engine number one",
            "starting two",
            "starting engine two",
            "starting engine number two",
            "config",
            "start the apu",
            "start apu",
            "go around flaps",
            "wipers off",
            "wipers slow",
            "wipers fast",
            "wipers slow intermittent",
            "wipers medium intermittent",
            "wipers fast intermittent",
            "seat belts on",
            "seat belts off",
            "seat belts auto",
            "set heading",
            "heading select",
            "set altitude",
            "altitude select",
            "set flight level",
            "flight level select",
            "set speed",
            "speed select",
            "set baro",
            "set qnh",
            "set altimeter",
            "set missed approach altitude",
            "pull speed",
            "manage speed",
            "pull heading",
            "manage heading",
            "pull altitude",
            "pull flight level",
            "manage altitude",
            "manage flight level",
            "set standard",
            "set runway track",
            "cabin crew arm slides and cross check",
            "cabin crew arm slides",
        };
}
